volumes: 
    langgraph-data: 
        driver: local 
services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./neo4j_data:/data
    environment:
      - NEO4J_AUTH=neo4j/neo4j!!!!
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4JLABS_PLUGINS=["apoc"]      
  langgraph-redis: 
      image: redis:6 
      healthcheck: 
          test: redis-cli ping 
          interval: 5s 
          timeout: 1s 
          retries: 5 
  langgraph-postgres: 
      image: postgres:16 
      ports: 
          - "5433:5432" 
      environment: 
          POSTGRES_DB: postgres 
          POSTGRES_USER: postgres 
          POSTGRES_PASSWORD: postgres 
      volumes: 
          - langgraph-data:/var/lib/postgresql/data 
      healthcheck: 
          test: pg_isready -U postgres 
          start_period: 10s 
          timeout: 1s 
          retries: 5 
          interval: 5s 
  langgraph-api: 
      image: ${IMAGE_NAME} 
      ports: 
          - "8123:8000" 
      depends_on: 
          langgraph-redis: 
              condition: service_healthy 
          langgraph-postgres: 
              condition: service_healthy 
      env_file: 
          - .env 
      environment: 
          REDIS_URI: redis://langgraph-redis:6379 
          LANGSMITH_API_KEY: ${LANGSMITH_API_KEY} 
          POSTGRES_URI: postgres://postgres:postgres@langgraph-postgres:5432/postgres?sslmode=disable       